# apiVersion: v1
# kind: Service
# metadata:
#   name: landmark-app-lb
#   namespace: landmark
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
#     service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxx, subnet-yyyyyy, subnet-zzzzzz"
# spec:
#   type: LoadBalancer
#   selector:
#     app: landmark-app
#   ports:
#     - port: 80
#       targetPort: 5000
#       protocol: TCP


apiVersion: v1
kind: Service
metadata:
  name: landmark-app-lb
  namespace: landmark
spec:
  type: LoadBalancer
  selector:
    app: landmark-svc-demo    # must match your pod labels
  ports:
  - name: http
    port: 80
    targetPort: 5000  # your app port
    protocol: TCP